app:
  image: glassfish:latest
  container_name: soap_app_1
  environment:
  - ADMIN_PASSWORD=91483993
  ports:
  - 141:8080
  - 14148:4848
  volumes:
  - ./logs:/usr/local/glassfish4/glassfish/domains/domain1/logs/
  links:
  - mariadb:db
mariadb:
  image: mariadb:10.1
  container_name: soap_db_1
  environment:
  - MYSQL_DATABASE=web
  - MYSQL_USER=admin
  - MYSQL_PASSWORD=admin
  - MYSQL_ROOT_PASSWORD=admin
  volumes:
  - /var/lib/mysql
  ports:
  - 14133:3306